name: 10
timestamp: 1531604429
version: 7
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1531604429
positions:
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  showcase: Showcase
  feature: Feature
  subfeature: Subfeature
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  menu:
    menu-2052: Menu
  sample:
    sample-1: 'Gantry 5'
    sample-2: 'Getting Started'
    sample-3: 'Key Features'
  messages:
    system-messages-3236: 'System Messages'
  position:
    position-footer: Footer
  copyright:
    copyright-7584: Copyright
  social:
    social-7439: Social
  branding:
    branding-4248: Branding
  mobile-menu:
    mobile-menu-3039: 'Mobile Menu'
inherit: {  }
