version: 2
preset:
  image: 'gantry-admin://images/layouts/offline.png'
  name: _offline
  timestamp: 1531604429
layout:
  /header/:
    -
      - 'logo-2694 30'
      - 'spacer-1193 70'
  /main/:
    -
      - system-messages-3027
    -
      - system-content-9329
  /footer/:
    -
      - position-footer
    -
      - 'copyright-3197 40'
      - 'spacer-3008 30'
      - 'branding-8703 30'
structure:
  header:
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-footer:
    attributes:
      key: footer
