version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1531604429
layout:
  /header/:
    -
      - 'logo-9742 30'
      - 'spacer-6749 70'
  /navigation/:
    -
      - menu-1554
  /main/:
    -
      - system-content-4562
  /footer/:
    -
      - position-footer
    -
      - 'copyright-6759 40'
      - 'spacer-1975 30'
      - 'branding-3374 30'
  offcanvas:
    -
      - mobile-menu-3750
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-footer:
    attributes:
      key: footer
