name: _body_only
timestamp: 1531604429
version: 7
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1531604429
positions: {  }
sections:
  main: Main
particles:
  messages:
    system-messages-3873: 'System Messages'
  content:
    system-content-6733: 'Page Content'
inherit: {  }
